databases:
  - name: hc-db
    plan: free
    databaseName: healthcheckdb
    user: hc

services:
  - type: web
    plan: free
    name: hc-django
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn hc.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DB
        value: "postgres"
      - key: DATABASE_URL
        fromDatabase:
          name: hc-db
          property: connectionString
      # Django Superuser Configuration
      - key: DJANGO_SUPERUSER_USERNAME
        sync: false

      - key: DJANGO_SUPERUSER_EMAIL
        sync: false

      - key: DJANGO_SUPERUSER_PASSWORD
        sync: false

      - key: SECRET_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 4
      - key: SITE_NAME
        value: "Healthchecks"
      - key: SITE_ROOT
        value: "https://hc.renhai.online"
      - key: ADMINS
        value: "hncdjzw@qq.com"
      - key: ALLOWED_HOSTS
        value: "hc.renhai.online,hc-django.onrender.com"
      - key: DEBUG
        sync: false
      - key: DEFAULT_FROM_EMAIL
        value: "mail@renhai.online"
      - key: EMAIL_HOST
        value: "smtp.mailgun.org"
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: EMAIL_HOST_USER
        value: "healthcheck@mail.renhai.online"
      - key: EMAIL_PORT
        value: "465"
      - key: EMAIL_USE_TLS
        value: "False"
      - key: EMAIL_USE_SSL
        value: "True"
      - key: EMAIL_USE_VERIFICATION
        value: "True"
      - key: REGISTRATION_OPEN
        value: "False"