databases:
  - name: hc-db
    plan: free
    databaseName: healthcheckdb
    user: hc

services:
  - type: web
    plan: free
    name: hc-django
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn hc.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DB
        value: "postgres"
      - key: DATABASE_URL
        fromDatabase:
          name: hc-db
          property: connectionString
      # Django Superuser Configuration
      - key: DJANGO_SUPERUSER_USERNAME
        sync: false

      - key: DJANGO_SUPERUSER_EMAIL
        sync: false

      - key: DJANGO_SUPERUSER_PASSWORD
        sync: false

      - key: SECRET_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 4
      - key: SITE_NAME
        sync: false
      - key: SITE_ROOT
        sync: false
      - key: ADMINS
        sync: false
      - key: ALLOWED_HOSTS
        sync: false
      - key: DEBUG
        sync: false
      - key: DEFAULT_FROM_EMAIL
        sync: false
      - key: EMAIL_HOST
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_PORT
        sync: false
      - key: EMAIL_USE_TLS
        sync: false
      - key: EMAIL_USE_SSL
        sync: false
      - key: EMAIL_USE_VERIFICATION
        sync: false
      - key: REGISTRATION_OPEN
        sync: false